# Generated by Django 3.0.8 on 2020-07-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diorama_layouts', '0003_auto_20200612_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diorama',
            name='imgpath',
            field=models.CharField(max_length=1024),
        ),
    ]
