# Generated by Django 3.0.7 on 2020-06-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diorama_layouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dioramas',
            old_name='imppath',
            new_name='imgpath',
        ),
    ]
