# Generated by Django 3.0.7 on 2020-06-12 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diorama_layouts', '0002_auto_20200612_0832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dioramas',
            new_name='Diorama',
        ),
    ]
